### ISSUE TITLE
Now I have update the modelbackend to support pytorch

### ISSUE THREAD

**Issue by mullerhai** [metarank/metarank#793]
Hi,  I think  it is perfect to support pytorch recommend model, and I have code this,If I success ,I will contribute these code for you

**Comment by shuttie** [comment]
@mullerhai We already did quite a lot of prototyping for the recommendations in Metarank, and using PyTorch models is indeed possible. But there are still some questions left before implementing it in Metarank.

As for now, Metarank runs on win/mac/linux, and supports both amd64 and arm64. Bringing Python runtime means that we should require user to build the JNI wrapper (not easy on mac/win) for the current combination of OS/CPU/python version, or pre-build all of them somehow (3 OS * 2 CPU * 3 Python versions = 18 separate builds).
* What should be the policy regarding supported OSes? Should we drop mac/win and only support linux x64/arm64?
* PyTorch is a framework, not a recommender model. Which particular recommendation model are you implementing on top of that? If it's matrix factorization based, are there non-torch (or maybe pure JVM) implementations of it? Librec is a good starting point.
* Metarank's API currently supports only reranking requests ("how do you reorder items A B C D to maximize CTR?"). Recommender is a retrieval task with some optional context ("for item A, what items are similar to it?" and  "for user B, what items are similar to their past activity?"). Are you also going to contribute the API and docs?

So what's your plan on that?

**Comment by mullerhai** [comment]
> @mullerhai We already did quite a lot of prototyping for the recommendations in Metarank, and using PyTorch models is indeed possible. But there are still some questions left before implementing it in Metarank.
> 
> As for now, Metarank runs on win/mac/linux, and supports both amd64 and arm64. Bringing Python runtime means that we should require user to build the JNI wrapper (not easy on mac/win) for the current combination of OS/CPU/python version, or pre-build all of them somehow (3 OS * 2 CPU * 3 Python versions = 18 separate builds).
> 
> * What should be the policy regarding supported OSes? Should we drop mac/win and only support linux x64/arm64?
> * PyTorch is a framework, not a recommender model. Which particular recommendation model are you implementing on top of that? If it's matrix factorization based, are there non-torch (or maybe pure JVM) implementations of it? Librec is a good starting point.
> * Metarank's API currently supports only reranking requests ("how do you reorder items A B C D to maximize CTR?"). Recommender is a retrieval task with some optional context ("for item A, what items are similar to it?" and  "for user B, what items are similar to their past activity?"). Are you also going to contribute the API and docs?
> 
> Apache Flink has a great policy for improvement proposals (https://cwiki.apache.org/confluence/display/Flink/Flink+Improvement+Proposals) for major changes, so everyone working on the project will be in sync on which big things are being planned.
> 
> I guess bringing Python-based recommendations in Metarank is indeed a major feature, so before starting writing code, it would be great to discuss on what is being planned :) If you have some ideas on implementation and overall design, we're always glad to discuss it either here in GH issues, or informally in our [community slack](https://metarank.ai/slack).

do you know javacpp-pytorch, could   bring libtorch cpp to java ,no need python env, the pytorch jni file will compile auto,  and did you know pytorch-fm project, I have rewrite it with scala code. so ,pytorch  fm scala model could run in metarank

**Comment by shuttie** [comment]
Spent some time playing with javacpp-torch, and I guess it can be worth digging a bit more. In simple words, we wanted to call python libs as then we don't need to rewrite torch-based algorithms from python to java: it's quite a brittle and time consuming route. Did it in the past, and instead of 1 hour, wasted weeks on that debugging some weird issues like algorithm not converging.

But deepfm repo shows that the actual neural network is built from a bunch of quite a simple building blocks with some minor data wrangling for inputs and outputs. It would be very helpful if you take any FM from DeepFM you like and make a prototype in Java/Scala - like a simple CLI app, no need to mess with Metarank API and stuff. You can take a traditional MovieLens dataset as an input, and check how it's working.

If you succeed (and I hope you will), I will wrap it with all the metarank-specific data-management code so it can be used as other types of algorithms, and throw some docs on the top.

**Comment by vgoloviznin** [comment]
Closing as an old issue
