### ISSUE TITLE
Training endpoint outputs: Response timed out

### ISSUE THREAD

**Issue by baelamri-ankorstore** [metarank/metarank#825]
The train endpoint outputs **Response timed out** (with curl and Python).
From the logs of Metarank, we don't see an error, we only know that it stops running on fetching 

```log
15:18:15.950 INFO a.m.f.redis.RedisClickthroughStore - fetched next page of 129 clickthroughs`
```

Metarank is not stuck, it justs stops trying to train the model.

**Comment by vgoloviznin** [comment]
Hey @baelamri-ankorstore, are you running the latest version of Metarank and what environment are you using (Docker\self-hosted, local)?

**Comment by shuttie** [comment]
@baelamri-ankorstore I have a couple of questions to triage the issue:
* is Metarank running in Docker or as a regular app?
* Can you post a longer log snippet when it stops working? What was happening before?
* If it's in docker, is the container running after you notice it is being stuck? Does Metarank reacts to other API calls?

**Comment by baelamri-ankorstore** [comment]
I'm working on a GKE Cluster, you can find my stack in the graph attached.

* each Metarank pod has 30Gi of memory and 5 cpus.
* redis hase 16 Gi of max memory
* We are way below the max usage of the redis: 7Gi

* If I ssh and htop in the metarank pods during the training process, not that much memory is used.

@shuttie 

* Docker is running in Kubernetes
* You can find the logs attached.
* Metarank responds without a problem. I call the metrics endpoint just after.


![image](https://user-images.githubusercontent.com/103923487/212015580-d74097de-e8bc-4cbf-bf94-3408021b9ca5.png)

[logs.txt](https://github.com/metarank/metarank/files/10399571/logs.txt)

**Comment by shuttie** [comment]
@baelamri-ankorstore I guess I may know what's going on. In 0.5.15 when running on kubernetes, the pod manifest lacks two important things related to memory usage:
* there was no explicit -Xmx JVM flag, so Metarank used default JVM heap size heuristics
* helm manifest was missing the resource requests and limits.
* there was no GC logging 

So when you called the /train endpoint:
* Metarank started pulling click-through events from Redis, which requires some extra memory to buffer them. 
* Kubelet for some reason (like node being low on free RAM) kills the pod, and you see the abrupt end of logs.
* Pod restarted, and you can send a /health request afterwards

We made a couple of improvements into memory management in [0.5.16](https://github.com/metarank/metarank/releases/tag/0.5.16), which are related to the issue you're observing. If it still OOMs with 1Gb heap (by default), I suggest:
* set the JVM_OPTS="-Xmx4g -verbose:gc" (so it will use 4g of JVM heap memory instead of 1g)
* also bump the memory requests in the helm manifest to something like 5g

**Comment by vgoloviznin** [comment]
Closing as an old issue
